### ISSUE TITLE
NuGet install fails

### ISSUE THREAD

**Issue by Nimgoble** [AfterbuyAxel/WPF-RichText-Editor#1]
NuGet install fails with error:

"Could not install package 'WpfRichText 1.0.16.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0,Profile=Client', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

**Comment by AfterbuyAxel** [comment]
The package is targetting the .NET Framework 4.5.
You have to install the Framework (http://go.microsoft.com/fwlink/p/?LinkId=245484) and set the target Framework in your Project (Project properties - Application - Target framwork).
![visualstudio2012_switch_target_framework](https://f.cloud.github.com/assets/1918472/929933/34afd882-fffa-11e2-965e-9c57606a72de.png)
