### ISSUE TITLE
Tabbing into control

### ISSUE THREAD

**Issue by fbelter** [AfterbuyAxel/WPF-RichText-Editor#2]
I have an issue with the control.

I have placed the control on a form with other controls.  The control is the 10th control on the form out of 20.  When the user tabs from the 9th control to the RichTextEditor, it goes to the control bar of the control.  Continuing to hit tab cycles through the control on the control bar of the RichTextEditor and never goes to the body.

I need it to tab directly into the body.  How do I do that?

By the way, this is a great control and it shows by they professional way it was done.

Frank

**Comment by AfterbuyAxel** [comment]
First you need to set a TabIndex on the RichTextBox "mainRTB" with TabIndex="x", so tabbing switches into the control.
Then you can set a KeyDown-Event onto the last button in the toolbar (InsertLink) to have it to Focus the mainRTB like this:

```
    private void insertLink_KeyDown(object sender, KeyEventArgs e)
    {
        switch (e.Key)
        {
            case Key.Tab:
                e.Handled = true;
                this.mainRTB.Focus();
                break;
            default:
                break;
        }
    }
```
