### ISSUE TITLE
Problem when using xceed 2.9

### ISSUE THREAD

**Issue by centrolutions** [AfterbuyAxel/WPF-RichText-Editor#3]
Getting errors because the xceed library updated their SelectedColorChanged delegate for their font color picker. Color is now nullable. From what I can tell, the new delegate should be:
```
private void FontColorPicker_SelectedColorChanged(object sender, RoutedPropertyChangedEventArgs<Color?> e)
{
   if (e.NewValue != null)
       this.mainRTB.Selection.ApplyPropertyValue(ForegroundProperty, ((Color)e.NewValue).ToString(CultureInfo.InvariantCulture));
}
```

**Comment by AfterbuyAxel** [comment]
Hi,
feel free to fix, I am no longer maintaining this project.
Thanks,
Axel
